---
title: "TYL Model figures"
author: "Casey Cazer"
date: "February 19, 2020"
output: html_document
---

```{r setup}
knitr::opts_knit$set(root.dir = '..') 
```

```{r}
library(ggplot2)
library(dplyr)
library(reshape2)
library(xlsx)
library(gridExtra)
library(plyr)

source('scripts/TYL func boxplots.R')
```

plot the difference in proportion resistant between TYL and no TYL control for each scenario (NI, DFM, AFTP, RWT, ALL).
Can take the difference between individual simulations because parameter values are the same for each simulation (due to random number seed)
```{r}
#automate loading data and calculating differences
datafiles<-c("NoTYL_NI_", "TYL_NI_", "NoTYL_NI_", "TYL_RWT_", "NoTYL_AFTP_", "TYL_AFTP_", "NoTYL_DFM_", "TYL_DFM_", "NoTYL_ALL_", "TYL_ALL_") #control followed by TYL intervention group. RWT control is the same as NoTYL_NI becuase with no tylosin there can be no withdrawal of tylosin. 

#load in proportion resistant
for (i in seq(1,length(datafiles),2)){
  
  notyl.feed <- read.table(paste("data/",datafiles[i],"Prop_feed_res.txt", sep=""), sep=",")
  tyl.feed <- read.table(paste("data/",datafiles[i+1],"Prop_feed_res.txt", sep=""), sep=",")
  
  notyl.water <- read.table(paste("data/",datafiles[i],"Prop_water_res.txt", sep=""), sep=",")
  tyl.water <- read.table(paste("data/",datafiles[i+1],"Prop_water_res.txt", sep=""), sep=",")
  
  notyl.pen <- read.table(paste("data/",datafiles[i],"Prop_pen_res.txt", sep=""), sep=",")
  tyl.pen <- read.table(paste("data/",datafiles[i+1],"Prop_pen_res.txt", sep=""), sep=",")
  
  diff.feed <- tyl.feed - notyl.feed
  diff.water <- tyl.water - notyl.water
  diff.pen <- tyl.pen - notyl.pen
  
  label <- paste(strsplit(datafiles[i+1], "_")[[1]][2], "_Prop_res", sep="")
  
  list <- list(tyl.feed, notyl.feed, diff.feed, notyl.water, tyl.water, diff.water, notyl.pen, tyl.pen, diff.pen)
  names(list) <- c("tyl.feed", "notyl.feed", "diff.feed", "notyl.water", "tyl.water", "diff.water", "notyl.pen", "tyl.pen", "diff.pen")
  
  assign(label, list)
}
rm(tyl.feed, notyl.feed, diff.feed, notyl.water, tyl.water, diff.water, notyl.pen, tyl.pen, diff.pen, list)


#other data for plotting
days<-read.table("data/NoTYL_NI_Days.txt", sep=",")
days<-as.numeric(days[,1]) - 50 #subtract burn-1n

quants<-c(0.01, 0.05, 0.25, 0.5, 0.75, 0.95, 0.99)

ltype=c("dotted", "dotdash", "longdash", "solid", "longdash", "dotdash", "dotted")
lcolor=c("black", "#F8766D", "#7CAE00", "#619CFF", "#7CAE00", "#F8766D", "black")


```


#plotting Prop Res in each intervention
```{r}
scenarios <- c("NI", "RWT", "DFM", "AFTP", "ALL")

#proportion resistant in pens, feed, water

#create figure of Prop res in pen for all scenarios
for (i in 1:length(scenarios)){
  data <- get(paste(scenarios[i], "_Prop_res", sep=""))
  plot <- func.boxplots(quants, data[['diff.pen']], days, ltype, lcolor, FALSE, TRUE, "Difference in Proportion Resistant")
  label <- paste("plot.pen.Pr.",scenarios[i], sep="")
  assign(label, plot)
  rm(plot, label, data)
}


#for feed, plot only at the end of every day to capture long-term trends and not focus on fluctations from feed being replaced every day
#create figure of Prop res in feed for all scenarios
for (i in 1:length(scenarios)){
  data <- get(paste(scenarios[i], "_Prop_res", sep=""))
  data <- data[['diff.feed']][seq(0,3433,24),]
  plot <- func.boxplots(quants, data, days[seq(0,3433,24)], ltype, lcolor, FALSE, TRUE, "Difference in Proportion Resistant")
  label <- paste("plot.feed.Pr.",scenarios[i], sep="")
  assign(label, plot)
  rm(plot, label, data)
}

#for water, also plot end of every day. Water is cleaned every two weeks
#create figure of Prop res in water for all scenarios
for (i in 1:length(scenarios)){
  data <- get(paste(scenarios[i], "_Prop_res", sep=""))
  data <- data[['diff.water']][seq(0,3433,24),]
  plot <- func.boxplots(quants, data, days[seq(0,3433,24)], ltype, lcolor, FALSE, TRUE, "Difference in Proportion Resistant")
  label <- paste("plot.water.Pr.",scenarios[i], sep="")
  assign(label, plot)
  rm(plot, label, data)
}


png('figures/Prop_env_res_interventions.png', height=4500, width=9000, res=300)
grid.arrange(plot.pen.Pr.RWT+
               scale_y_continuous(limits=c(0,0.1))+
               ylab("Difference in Proportion Resistant: Pen")+
               xlab("")+
               ggtitle("RWT"), 
             plot.pen.Pr.DFM+
               scale_y_continuous(limits=c(0,0.1))+
               ylab("")+
               xlab("")+
               ggtitle("DFM"), 
             plot.pen.Pr.AFTP+
               scale_y_continuous(limits=c(0,0.1))+
               ylab("")+
               xlab("")+
               ggtitle("AFTP"), 
             plot.pen.Pr.ALL+
               scale_y_continuous(limits=c(0,0.1))+
               ylab("")+
               xlab("")+
               ggtitle("ALL"),
             plot.feed.Pr.RWT+
               scale_y_continuous(limits=c(0,0.1))+
               ylab("Difference in Proportion Resistant: Feed")+
               xlab(""), 
             plot.feed.Pr.DFM+
               scale_y_continuous(limits=c(0,0.1))+
               ylab("")+
               xlab(""), 
             plot.feed.Pr.AFTP+
               scale_y_continuous(limits=c(0,0.1))+
               ylab("")+
               xlab(""), 
             plot.feed.Pr.ALL+
               scale_y_continuous(limits=c(0,0.1))+
               ylab("")+
               xlab(""),
             plot.water.Pr.RWT+
               scale_y_continuous(limits=c(0,0.1))+
               ylab("Difference in Proportion Resistant: Water")+
               xlab("Days"), 
             plot.water.Pr.DFM+
               scale_y_continuous(limits=c(0,0.1))+
               ylab("")+
               xlab("Days"), 
             plot.water.Pr.AFTP+
               scale_y_continuous(limits=c(0,0.1))+
               ylab("")+
               xlab("Days"), 
             plot.water.Pr.ALL+
               scale_y_continuous(limits=c(0,0.1))+
               ylab("")+
               xlab("Days"),ncol=4)
dev.off()


#full y-axis
png('figures/Prop_env_res_interventions0_100.png', height=4500, width=9000, res=300)
grid.arrange(plot.pen.Pr.RWT+
               ylab("Pen: Diff. Prop. Resistant")+
               xlab("")+
               ggtitle("RWT"), 
             plot.pen.Pr.DFM+
               ylab("")+
               xlab("")+
               ggtitle("DFM"), 
             plot.pen.Pr.AFTP+
               ylab("")+
               xlab("")+
               ggtitle("AFTP"), 
             plot.pen.Pr.ALL+
               ylab("")+
               xlab("")+
               ggtitle("ALL"),
             plot.feed.Pr.RWT+
               ylab("Feed: Diff. Prop. Resistant")+
               xlab(""), 
             plot.feed.Pr.DFM+
               ylab("")+
               xlab(""), 
             plot.feed.Pr.AFTP+
               ylab("")+
               xlab(""), 
             plot.feed.Pr.ALL+
               ylab("")+
               xlab(""),
             plot.water.Pr.RWT+
               ylab("Water: Diff. Prop. Resistant")+
               xlab("Days"), 
             plot.water.Pr.DFM+
               ylab("")+
               xlab("Days"), 
             plot.water.Pr.AFTP+
               ylab("")+
               xlab("Days"), 
             plot.water.Pr.ALL+
               ylab("")+
               xlab("Days"),ncol=4)
dev.off()

#for publication, improve label positioning outside plots so that all plots are same size
```

```{r}
save.image('RData/Model Prop Res Env Figs.RData')
```